import type { Perfume } from './PerfumeShelf'

/**
 * Sample perfume data used as fallback when the Supabase database is empty.
 * Includes the JPG Le Male lineup, YSL EDP, and Azzaro The Most Wanted.
 */
export const samplePerfumes: Perfume[] = [
  // ── JPG Le Male Lineup ───────────────────────────────────────────────
  {
    id: 'sample-le-male-edt',
    name: 'Le Male',
    brand: 'Jean Paul Gaultier',
    category: 'Designer',
    concentration: 'Eau de Toilette',
    occasion: 'Casual',
    notes: 'Top: Lavender, Mint, Bergamot, Cardamom. Heart: Cinnamon, Cumin, Orange Blossom. Base: Vanilla, Amber, Tonka Bean, Sandalwood, Cedar',
    image_url: '',
    shelf_row: 1,
    rating: 4.5,
    longevity_hours: 7,
    ideal_season: 'Fall',
  },
  {
    id: 'sample-le-male-le-parfum',
    name: 'Le Male Le Parfum',
    brand: 'Jean Paul Gaultier',
    category: 'Designer',
    concentration: 'Eau de Parfum',
    occasion: 'Date Night',
    notes: 'Top: Cardamom, Iris. Heart: Lavandin, Tuberose. Base: Vanilla, Woody Notes, Oriental Accord',
    image_url: '',
    shelf_row: 1,
    rating: 4.7,
    longevity_hours: 9,
    ideal_season: 'Winter',
  },
  {
    id: 'sample-le-male-elixir',
    name: 'Le Male Elixir',
    brand: 'Jean Paul Gaultier',
    category: 'Designer',
    concentration: 'Parfum',
    occasion: 'Date Night',
    notes: 'Top: Lavender, Mint. Heart: Honey, Tuberose, Rose. Base: Vanilla, Amber, Tonka Bean, Benzoin',
    image_url: '',
    shelf_row: 1,
    rating: 4.8,
    longevity_hours: 10,
    ideal_season: 'Winter',
  },
  {
    id: 'sample-ultra-male',
    name: 'Ultra Male',
    brand: 'Jean Paul Gaultier',
    category: 'Designer',
    concentration: 'Eau de Toilette Intense',
    occasion: 'Party',
    notes: 'Top: Pear, Bergamot, Black Lavender, Mint. Heart: Cinnamon, Sage, Clary Sage. Base: Vanilla, Amber, Patchouli, Cedar',
    image_url: '',
    shelf_row: 1,
    rating: 4.6,
    longevity_hours: 8,
    ideal_season: 'Fall',
  },
  {
    id: 'sample-le-beau',
    name: 'Le Beau Le Parfum',
    brand: 'Jean Paul Gaultier',
    category: 'Designer',
    concentration: 'Eau de Parfum',
    occasion: 'Date Night',
    notes: 'Top: Green Mandarin. Heart: Coconut, Ambroxan. Base: Sandalwood, Tonka Bean, Vanilla',
    image_url: '',
    shelf_row: 1,
    rating: 4.4,
    longevity_hours: 8,
    ideal_season: 'Summer',
  },

  // ── YSL EDP ──────────────────────────────────────────────────────────
  {
    id: 'sample-ysl-la-nuit',
    name: 'La Nuit de L\'Homme',
    brand: 'Yves Saint Laurent',
    category: 'Designer',
    concentration: 'Eau de Parfum',
    occasion: 'Date Night',
    notes: 'Top: Cardamom, Bergamot. Heart: Lavender, Iris, Cedar. Base: Vetiver, Coumarin, Amber',
    image_url: '',
    shelf_row: 2,
    rating: 4.3,
    longevity_hours: 6,
    ideal_season: 'Fall',
  },

  // ── Azzaro ───────────────────────────────────────────────────────────
  {
    id: 'sample-azzaro-most-wanted',
    name: 'The Most Wanted',
    brand: 'Azzaro',
    category: 'Designer',
    concentration: 'Eau de Parfum Intense',
    occasion: 'Date Night',
    notes: 'Top: Ginger, Cardamom, Lavender. Heart: Toffee, Iris, Cinnamon. Base: Amber, Patchouli, Vanilla, Benzoin',
    image_url: '',
    shelf_row: 3,
    rating: 4.6,
    longevity_hours: 9,
    ideal_season: 'Winter',
  },
]
